apiVersion: v1
kind: Service
metadata:
  name: "prysm-grafana"
  labels: {{- include "prysm-node.grafanaLabels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.grafanaConfig.listenPort }}
      targetPort: {{ .Values.grafanaConfig.listenPort }}
      protocol: TCP
      name: grafana
  selector:
    {{- include "prysm-node.grafanaSelectorLabels" . | nindent 4 }}
