apiVersion: v1
kind: Service
metadata:
  name: "prysm-prometheus"
  labels: {{- include "prysm-node.prometheusLabels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.prometheusConfig.listenPort }}
      targetPort: {{ .Values.prometheusConfig.listenPort }}
      protocol: TCP
      name: prometheus
  selector:
    {{- include "prysm-node.prometheusSelectorLabels" . | nindent 4 }}
