apiVersion: v1
kind: Service
metadata:
  name: "prysm-rpc"
  labels:
    {{- include "prysm-node.beaconLabels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.beaconConfig.rpcPort }}
      targetPort: {{ .Values.beaconConfig.rpcPort }}
      protocol: TCP
      name: rpc
  selector:
    {{- include "prysm-node.beaconSelectorLabels" . | nindent 4 }}
