apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "prysm-stats"
  labels: {{- include "prysm-node.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.statsConfig.volume.storageClass }}
  storageClassName: {{ .Values.statsConfig.volume.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.statsConfig.volume.size }}
